version: '3'

services:
  database-nulp:
    image: 'postgres'
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: nulp_database
    ports:
      - '5434:5432'
    volumes:
      - database-data-nulp:/var/lib/postgresql/data/
volumes:
  database-data-nulp:
